const recentProducts = [
  {
    id: 1,
    productName: "ASOS Ridley High Waist",
    price: "$79.49",
    quantity: 82,
    status: "Active",
    amount: "$6,518.18",
  },
  {
    id: 2,
    productName: "Marco Lightweight Shirt",
    price: "$128.50",
    quantity: 37,
    status: "Pending",
    amount: "$4,754.50",
  },
  {
    id: 3,
    productName: "Half Sleeve Shirt",
    price: "$39.99",
    quantity: 64,
    status: "Done",
    amount: "$2,559.36",
  },
  {
    id: 4,
    productName: "Lightweight Jacket",
    price: "$20.00",
    quantity: 184,
    status: "Progress",
    amount: "$3,680.00",
  },
  {
    id: 5,
    productName: "Marco Shoes",
    price: "$28.49",
    quantity: 69,
    status: "Pending",
    amount: "$1,965.81",
  },
  {
    id: 6,
    productName: "ASOS Ridley High Waist",
    price: "$79.49",
    quantity: 82,
    status: "Done",
    amount: "$6,518.18",
  },
];
const latestUpdate = [
  {
    title: "Total Sales",
    subtitle: "New Sale 20.5k",
    count: "45K",
    icon: "mdi mdi-sale",
    bgColor: "bg-soft-info",
    variant: "text-info",
  },
  {
    title: "Product Cost",
    subtitle: "Total Cost 12.3k",
    count: "13K",
    icon: "mdi mdi-autorenew",
    bgColor: "bg-soft-warning",
    variant: "text-warning",
  },
  {
    title: "Satisfaction Users",
    subtitle: "Total Users 26M",
    count: "16M",
    icon: "mdi mdi-emoticon-happy-outline",
    bgColor: "bg-soft-pink",
    variant: "text-pink",
  },
  {
    title: "Product Income",
    subtitle: "Income 65.4k",
    count: "75K",
    icon: "mdi mdi-cash-multiple",
    bgColor: "bg-soft-dark",
    variant: "text-dark",
  },
];
export { recentProducts, latestUpdate };
