const MENU_ITEMS = [
  {
    key: "navigation",
    label: "Navigation",
    isTitle: true,
  },
  {
    key: "dashboard",
    label: "Dashboard",
    isTitle: false,
    icon: "fe-airplay",
    url: "/dashboard",
    badge: {
      variant: "success",
      text: "7",
    },
  },
  {
    key: "apps",
    label: "Apps",
    isTitle: true,
  },
  {
    key: "apps-calendar",
    label: "Calendar",
    isTitle: false,
    icon: "fe-calendar",
    url: "/apps/calendar",
  },
  {
    key: "apps-email",
    label: "Email",
    isTitle: false,
    icon: "fe-mail",
    children: [
      {
        key: "email-inbox",
        label: "Inbox",
        url: "/apps/email/inbox",
        parentKey: "apps-email",
      },
      {
        key: "email-read",
        label: "Read Email",
        url: "/apps/email/read",
        parentKey: "apps-email",
      },
      {
        key: "email-compose",
        label: "Compose Email",
        url: "/apps/email/compose",
        parentKey: "apps-email",
      },
    ],
  },
  {
    key: "apps-members",
    label: "Members",
    isTitle: false,
    icon: "fe-users",
    url: "/apps/member",
  },
  {
    key: "custom",
    label: "Custom",
    isTitle: true,
  },
  {
    key: "auth",
    label: "Auth Pages",
    isTitle: false,
    icon: "fe-shield",
    children: [
      {
        key: "auth-login",
        label: "Login",
        url: "/auth/login",
        parentKey: "auth",
      },
      {
        key: "auth-register",
        label: "Register",
        url: "/auth/register",
        parentKey: "auth",
      },
      {
        key: "auth-recover-password",
        label: "Recover Password",
        url: "/auth/recover-password",
        parentKey: "auth",
      },
      {
        key: "auth-lock-screen",
        label: "Lock Screen",
        url: "/auth/lock-screen",
        parentKey: "auth",
      },
      {
        key: "auth-logout",
        label: "Logout",
        url: "/auth/logout",
        parentKey: "auth",
      },
      {
        key: "auth-confirm-mail",
        label: "Confirm Mail",
        url: "/auth/confirm-mail",
        parentKey: "auth",
      },
      {
        key: "error-404",
        label: "Error 404",
        url: "/error-404",
        parentKey: "auth",
      },
      {
        key: "error-404-alt",
        label: "Error 404-alt",
        url: "/error-404-alt",
        parentKey: "auth",
      },
      {
        key: "error-500",
        label: "Error 500",
        url: "/error-500",
        parentKey: "auth",
      },
    ],
  },
  {
    key: "pages",
    label: "Extra Pages",
    isTitle: false,
    icon: "fe-book-open",
    children: [
      {
        key: "pages-starter",
        label: "Starter Page",
        url: "/pages/starter",
        parentKey: "pages",
      },
      {
        key: "pages-timeline",
        label: "Timeline",
        url: "/pages/timeline",
        parentKey: "pages",
      },
      {
        key: "pages-profile",
        label: "Profile",
        url: "/pages/profile",
        parentKey: "pages",
      },
      {
        key: "pages-about",
        label: "About Us",
        url: "/pages/about",
        parentKey: "pages",
      },
      {
        key: "pages-contact",
        label: "Contact Us",
        url: "/pages/contact",
        parentKey: "pages",
      },
      {
        key: "pages-faq",
        label: "FAQs",
        url: "/pages/faq",
        parentKey: "pages",
      },
      {
        key: "pages-pricing",
        label: "Pricing",
        url: "/pages/pricing",
        parentKey: "pages",
      },
      {
        key: "pages-maintenance",
        label: "Maintenance",
        url: "/pages/maintenance",
        parentKey: "pages",
      },
      {
        key: "pages-coming-soon",
        label: "Coming Soon",
        url: "/pages/coming-soon",
        parentKey: "pages",
      },
      {
        key: "pages-invoice",
        label: "Invoice",
        url: "/pages/invoice",
        parentKey: "pages",
      },
    ],
  },
  {
    key: "layouts",
    label: "Layouts",
    isTitle: false,
    icon: "fe-layout",
    badge: {
      variant: "danger",
      text: "new",
    },
    children: [
      {
        key: "horizontal",
        label: "Horizontal",
        target: "_blank",
        url: "/horizontal",
        parentKey: "pages",
      },
      {
        key: "detached",
        label: "Detached",
        target: "_blank",
        url: "/detached",
        parentKey: "pages",
      },
      {
        key: "dark-mode",
        label: "Dark Mode",
        target: "_blank",
        url: "/dark-mode",
        parentKey: "pages",
      },
      {
        key: "compact-sidebar",
        label: "Compact",
        target: "_blank",
        url: "/compact-sidebar",
        parentKey: "pages",
      },
      {
        key: "icon-view",
        label: "Icon View",
        target: "_blank",
        url: "/icon-view",
        parentKey: "pages",
      },
      {
        key: "full-view",
        label: "Full View",
        target: "_blank",
        url: "/full-view",
        parentKey: "pages",
      },
    ],
  },
  {
    key: "components",
    label: "Components",
    isTitle: true,
  },
  {
    key: "ui",
    label: "UI Kit",
    isTitle: false,
    icon: "fe-briefcase",
    children: [
      {
        key: "ui-accordions",
        label: "Accordions",
        url: "/ui/accordions",
        parentKey: "ui",
      },
      {
        key: "ui-alerts",
        label: "Alerts",
        url: "/ui/alerts",
        parentKey: "ui",
      },
      {
        key: "ui-avatars",
        label: "Avatars",
        url: "/ui/avatars",
        parentKey: "ui",
      },
      {
        key: "ui-badges",
        label: "Badges",
        url: "/ui/badges",
        parentKey: "ui",
      },
      {
        key: "ui-breadcrumb",
        label: "Breadcrumb",
        url: "/ui/breadcrumb",
        parentKey: "ui",
      },
      {
        key: "ui-buttons",
        label: "Buttons",
        url: "/ui/buttons",
        parentKey: "ui",
      },
      {
        key: "ui-cards",
        label: "Cards",
        url: "/ui/cards",
        parentKey: "ui",
      },
      {
        key: "ui-carousel",
        label: "Carousel",
        url: "/ui/carousel",
        parentKey: "ui",
      },
      {
        key: "ui-collapse",
        label: "Collapse",
        url: "/ui/collapse",
        parentKey: "ui",
      },
      {
        key: "ui-dropdowns",
        label: "Dropdowns",
        url: "/ui/dropdowns",
        parentKey: "ui",
      },
      {
        key: "ui-embed-video",
        label: "Embed Video",
        url: "/ui/embed-video",
        parentKey: "ui",
      },
      {
        key: "ui-grid",
        label: "Grid",
        url: "/ui/grid",
        parentKey: "ui",
      },
      {
        key: "ui-list-group",
        label: "List Group",
        url: "/ui/list-group",
        parentKey: "ui",
      },
      {
        key: "ui-modals",
        label: "modals",
        url: "/ui/modals",
        parentKey: "ui",
      },
      {
        key: "ui-notifications",
        label: "Notifications",
        url: "/ui/notifications",
        parentKey: "ui",
      },
      {
        key: "ui-offcanvas",
        label: "Offcanvas",
        url: "/ui/offcanvas",
        parentKey: "ui",
      },
      {
        key: "ui-placeholders",
        label: "Placeholders",
        url: "/ui/placeholders",
        parentKey: "ui",
      },
      {
        key: "ui-pagination",
        label: "Pagination",
        url: "/ui/pagination",
        parentKey: "ui",
      },
      {
        key: "ui-popovers",
        label: "Popovers",
        url: "/ui/popovers",
        parentKey: "ui",
      },
      {
        key: "ui-progress",
        label: "Progress",
        url: "/ui/progress",
        parentKey: "ui",
      },
      {
        key: "ui-spinners",
        label: "Spinners",
        url: "/ui/spinners",
        parentKey: "ui",
      },
      {
        key: "ui-tabs",
        label: "Tabs",
        url: "/ui/tabs",
        parentKey: "ui",
      },
      {
        key: "ui-tooltips",
        label: "Tooltips",
        url: "/ui/tooltips",
        parentKey: "ui",
      },
      {
        key: "ui-typography",
        label: "Typography",
        url: "/ui/typography",
        parentKey: "ui",
      },
    ],
  },
  {
    key: "extended",
    label: "Extended UI",
    isTitle: false,
    icon: "fe-target",
    badge: {
      variant: "info",
      text: "Hot",
    },
    children: [
      {
        key: "extended-nestable",
        label: "Nestable List",
        url: "/extended/nestable",
        parentKey: "extended",
      },
      {
        key: "range-slider",
        label: "Range Slider",
        url: "/extended/range-slider",
        parentKey: "extended",
      },
      {
        key: "extended-tour",
        label: "Tour Page",
        url: "/extended/tour",
        parentKey: "extended",
      },
      {
        key: "scrollspy",
        label: "Scrollspy",
        url: "/extended/scrollspy",
        parentKey: "extended",
      },
      {
        key: "extended-scrollbar",
        label: "Scrollbar",
        url: "/extended/scrollbar",
        parentKey: "extended",
      },
      {
        key: "extended-sweet-alert",
        label: "Sweet Alert",
        url: "/extended/sweet-alert",
        parentKey: "extended",
      },
    ],
  },
  {
    key: "ui-widgets",
    label: "Widgets",
    isTitle: false,
    icon: "fe-gift",
    url: "/ui/widgets",
  },
  {
    key: "icons",
    label: "Icons",
    isTitle: false,
    icon: "fe-box",
    children: [
      {
        key: "icons-two-tone",
        label: "Two Tone",
        url: "/ui/icons/two-tone",
        parentKey: "icons",
      },
      {
        key: "icons-colored",
        label: "Colored",
        url: "/ui/icons/colored",
        parentKey: "icons",
      },
      {
        key: "icons-feather",
        label: "Feather",
        url: "/ui/icons/feather",
        parentKey: "icons",
      },
      {
        key: "icons-material",
        label: "Material Design",
        url: "/ui/icons/material",
        parentKey: "icons",
      },
      {
        key: "icons-dripicons",
        label: "Dripicons",
        url: "/ui/icons/dripicons",
        parentKey: "icons",
      },
      {
        key: "icons-font-awesome",
        label: "Font Awesome 5",
        url: "/ui/icons/font-awesome",
        parentKey: "icons",
      },
      {
        key: "icons-remix",
        label: "Remix icons",
        url: "/ui/icons/remix",
        parentKey: "icons",
      },
      {
        key: "icons-unicons",
        label: "Unicons",
        url: "/ui/icons/unicons",
        parentKey: "icons",
      },
    ],
  },
  {
    key: "charts",
    label: "Charts",
    isTitle: false,
    icon: "fe-bar-chart-line-",
    children: [
      {
        key: "apex-charts",
        label: "Apex Charts",
        url: "/charts/apex",
        parentKey: "charts",
      },
      {
        key: "chartjs-charts",
        label: "Chartjs Charts",
        url: "/charts/chartjs",
        parentKey: "charts",
      },
      {
        key: "sparklines-charts",
        label: "Sparklines Charts",
        url: "/charts/sparklines",
        parentKey: "charts",
      },
    ],
  },
  {
    key: "forms",
    label: "Forms",
    isTitle: false,
    icon: "fe-disc",
    children: [
      {
        key: "forms-basic-elements",
        label: "Basic Elements",
        url: "/forms/basic-elements",
        parentKey: "forms",
      },
      {
        key: "forms-advanced",
        label: "Form Advanced",
        url: "/forms/form-advanced",
        parentKey: "forms",
      },
      {
        key: "forms-validation",
        label: "Validation",
        url: "/forms/validation",
        parentKey: "forms",
      },
      {
        key: "forms-pickers",
        label: "Pickers",
        url: "/forms/pickers",
        parentKey: "forms",
      },
      {
        key: "forms-wizard",
        label: "Wizard",
        url: "/forms/wizard",
        parentKey: "forms",
      },
      {
        key: "forms-masks",
        label: "Masks",
        url: "/forms/masks",
        parentKey: "forms",
      },
      {
        key: "forms-file-uploads",
        label: "File Uploads",
        url: "/forms/file-uploads",
        parentKey: "forms",
      },
      {
        key: "forms-editors",
        label: "Editors",
        url: "/forms/editors",
        parentKey: "forms",
      },
    ],
  },
  {
    key: "tables",
    label: "Tables",
    isTitle: false,
    icon: "fe-grid",
    children: [
      {
        key: "tables-basic",
        label: "Basic Tables",
        url: "/ui/tables/basic-tables",
        parentKey: "tables",
      },
      {
        key: "tables-data",
        label: "Data Tables",
        url: "/ui/tables/data-tables",
        parentKey: "tables",
      },
      // {
      //   key: 'tables-responsive',
      //   label: 'RC Tables',
      //   url: '/ui/tables/RC-tables',
      //   parentKey: 'tables',
      // },
    ],
  },
  {
    key: "maps",
    label: "Maps",
    isTitle: false,
    icon: "fe-map",
    children: [
      {
        key: "maps-google-maps",
        label: "Google maps",
        url: "/ui/maps/google-maps",
        parentKey: "maps",
      },
      {
        key: "maps-vector-maps",
        label: "Vector maps",
        url: "/ui/maps/vector-maps",
        parentKey: "maps",
      },
    ],
  },
  {
    key: "multi-level",
    label: "Multi Level",
    isTitle: false,
    icon: "fe-folder-plus",
    children: [
      {
        key: "second-level",
        label: "Second Level",
        url: "/",
        parentKey: "multi-level",
        children: [
          {
            key: "second-level-1",
            label: "Item 1",
            url: "/",
            parentKey: "second-level",
          },
          {
            key: "second-level-2",
            label: "Item 2",
            url: "/",
            parentKey: "second-level",
          },
        ],
      },
      {
        key: "third-level",
        label: "Third Level",
        url: "/",
        parentKey: "multi-level",
        children: [
          {
            key: "third-level-1",
            label: "Item 1",
            url: "/",
            parentKey: "third-level",
          },
          {
            key: "third-level-2",
            label: "Item 2",
            url: "/",
            parentKey: "third-level",
            children: [
              {
                key: "third-level-2-1",
                label: "Item 2.1",
                url: "/",
                parentKey: "third-level-2",
              },
              {
                key: "third-level-2-2",
                label: "Item 2.2",
                url: "/",
                parentKey: "third-level-2",
              },
            ],
          },
        ],
      },
    ],
  },
];
const HORIZONTAL_MENU_ITEMS = [
  {
    key: "dashboard",
    icon: "fe-airplay",
    label: "Dashboard",
    url: "/dashboard",
    isTitle: false,
  },
  {
    key: "apps",
    icon: "fe-grid",
    label: "Apps",
    isTitle: true,
    children: [
      {
        key: "apps-calendar",
        icon: "fe-calendar me-2",
        label: "Calendar",
        url: "/apps/calendar",
        parentKey: "apps",
      },
      {
        key: "apps-email",
        icon: "fe-mail me-2",
        label: "Email",
        parentKey: "apps",
        children: [
          {
            key: "email-inbox",
            label: "Inbox",
            url: "/apps/email/inbox",
            parentKey: "apps-email",
          },
          {
            key: "email-read",
            label: "Read Email",
            url: "/apps/email/read",
            parentKey: "apps-email",
          },
          {
            key: "email-compose",
            label: "Compose Email",
            url: "/apps/email/compose",
            parentKey: "apps-email",
          },
        ],
      },
      {
        key: "apps-member",
        icon: "fe-users me-2",
        label: "Member",
        url: "/apps/member",
        parentKey: "apps",
      },
    ],
  },
  {
    key: "base-ui",
    icon: "fe-briefcase me-2",
    label: "Base UI",
    isTitle: true,
    children: [
      {
        key: "ui-accordions",
        label: "Accordions",
        url: "/ui/accordions",
        parentKey: "ui",
      },
      {
        key: "ui-alerts",
        label: "Alerts",
        url: "/ui/alerts",
        parentKey: "ui",
      },
      {
        key: "ui-avatars",
        label: "Avatars",
        url: "/ui/avatars",
        parentKey: "ui",
      },
      {
        key: "ui-badges",
        label: "Badges",
        url: "/ui/badges",
        parentKey: "ui",
      },
      {
        key: "ui-breadcrumb",
        label: "Breadcrumb",
        url: "/ui/breadcrumb",
        parentKey: "ui",
      },
      {
        key: "ui-buttons",
        label: "Buttons",
        url: "/ui/buttons",
        parentKey: "ui",
      },
      {
        key: "ui-cards",
        label: "Cards",
        url: "/ui/cards",
        parentKey: "ui",
      },
      {
        key: "ui-carousel",
        label: "Carousel",
        url: "/ui/carousel",
        parentKey: "ui",
      },
      {
        key: "ui-collapse",
        label: "Collapse",
        url: "/ui/collapse",
        parentKey: "ui",
      },
      {
        key: "ui-dropdowns",
        label: "Dropdowns",
        url: "/ui/dropdowns",
        parentKey: "ui",
      },
      {
        key: "ui-embed-video",
        label: "Embed Video",
        url: "/ui/embed-video",
        parentKey: "ui",
      },
      {
        key: "ui-grid",
        label: "Grid",
        url: "/ui/grid",
        parentKey: "ui",
      },
      {
        key: "ui-list-group",
        label: "List Group",
        url: "/ui/list-group",
        parentKey: "ui",
      },
      {
        key: "ui-modals",
        label: "Modals",
        url: "/ui/modals",
        parentKey: "ui",
      },
      {
        key: "ui-notifications",
        label: "Notifications",
        url: "/ui/notifications",
        parentKey: "ui",
      },
      {
        key: "ui-offcanvas",
        label: "Offcanvas",
        url: "/ui/offcanvas",
        parentKey: "ui",
      },
      {
        key: "ui-placeholders",
        label: "Placeholders",
        url: "/ui/placeholders",
        parentKey: "ui",
      },
      {
        key: "ui-pagination",
        label: "Pagination",
        url: "/ui/pagination",
        parentKey: "ui",
      },
      {
        key: "ui-popovers",
        label: "Popovers",
        url: "/ui/popovers",
        parentKey: "ui",
      },
      {
        key: "ui-progress",
        label: "Progress",
        url: "/ui/progress",
        parentKey: "ui",
      },
      {
        key: "ui-spinners",
        label: "Spinners",
        url: "/ui/spinners",
        parentKey: "ui",
      },
      {
        key: "ui-tabs",
        label: "Tabs",
        url: "/ui/tabs",
        parentKey: "ui",
      },
      {
        key: "ui-tooltips",
        label: "Tooltips",
        url: "/ui/tooltips",
        parentKey: "ui",
      },
      {
        key: "ui-typography",
        label: "Typography",
        url: "/ui/typography",
        parentKey: "ui",
      },
    ],
  },
  {
    key: "components",
    icon: "uil-package",
    label: "Components",
    isTitle: true,
    children: [
      {
        key: "ui-widgets",
        icon: "fe-gift me-2",
        label: "Widgets",
        url: "/ui/widgets",
        parentKey: "components",
      },
      {
        key: "extended",
        icon: "fe-target me-2",
        label: "Extended UI",
        parentKey: "components",
        children: [
          {
            key: "extended-nestable",
            label: "Nestable List",
            url: "/extended/nestable",
            parentKey: "extended",
          },
          {
            key: "extended-tour",
            label: "Tour Page",
            url: "/extended/tour",
            parentKey: "extended",
          },
          {
            key: "range-slider",
            label: "Range Slider",
            url: "/extended/range-slider",
            parentKey: "extended",
          },
          {
            key: "extended-scrollbar",
            label: "Scrollbar",
            url: "/extended/scrollbar",
            parentKey: "extended",
          },
          {
            key: "scrollspy",
            label: "Scrollspy",
            url: "/extended/scrollspy",
            parentKey: "extended",
          },
          {
            key: "extended-sweet-alert",
            label: "Sweet Alert",
            url: "/extended/sweet-alert",
            parentKey: "extended",
          },
        ],
      },
      {
        key: "forms",
        icon: "fe-disc me-2",
        label: "Forms",
        parentKey: "components",
        children: [
          {
            key: "forms-basic-elements",
            label: "Basic Elements",
            url: "/forms/basic-elements",
            parentKey: "forms",
          },
          {
            key: "forms-advanced",
            label: "Form Advanced",
            url: "/forms/form-advanced",
            parentKey: "forms",
          },
          {
            key: "forms-validation",
            label: "Validation",
            url: "/forms/validation",
            parentKey: "forms",
          },
          {
            key: "forms-pickers",
            label: "Pickers",
            url: "/forms/pickers",
            parentKey: "forms",
          },
          {
            key: "forms-wizard",
            label: "Wizard",
            url: "/forms/wizard",
            parentKey: "forms",
          },
          {
            key: "forms-masks",
            label: "Masks",
            url: "/forms/masks",
            parentKey: "forms",
          },
          {
            key: "forms-file-uploads",
            label: "File Uploads",
            url: "/forms/file-uploads",
            parentKey: "forms",
          },
          {
            key: "forms-editors",
            label: "Editors",
            url: "/forms/editors",
            parentKey: "forms",
          },
        ],
      },
      {
        key: "charts",
        icon: "fe-bar-chart-line- me-2",
        label: "Charts",
        parentKey: "components",
        children: [
          {
            key: "apex-charts",
            label: "Apex Charts",
            url: "/charts/apex",
            parentKey: "charts",
          },
          {
            key: "chartjs-charts",
            label: "Chartjs Charts",
            url: "/charts/chartjs",
            parentKey: "charts",
          },
          {
            key: "sparklines-charts",
            label: "Sparklines Charts",
            url: "/charts/sparklines",
            parentKey: "charts",
          },
        ],
      },
      {
        key: "tables",
        icon: "fe-grid me-2",
        label: "Tables",
        parentKey: "components",
        children: [
          {
            key: "tables-basic",
            label: "Basic Tables",
            url: "/ui/tables/basic-tables",
            parentKey: "tables",
          },
          {
            key: "tables-data",
            label: "Data Tables",
            url: "/ui/tables/data-tables",
            parentKey: "tables",
          },
          // {
          //   key: 'tables-responsive',
          //   label: 'Responsive Tables',
          //   url: '/ui/tables/RC-tables',
          //   parentKey: 'tables',
          // },
        ],
      },
      {
        key: "icons",
        icon: "fe-box me-2",
        label: "Icons",
        parentKey: "components",
        children: [
          {
            key: "icons-two-tone",
            label: "Two Tone",
            url: "/ui/icons/two-tone",
            parentKey: "icons",
          },
          {
            key: "icons-colored",
            label: "Colored",
            url: "/ui/icons/colored",
            parentKey: "icons",
          },
          {
            key: "icons-feather",
            label: "Feather",
            url: "/ui/icons/feather",
            parentKey: "icons",
          },
          {
            key: "icons-material",
            label: "Material Design",
            url: "/ui/icons/material",
            parentKey: "icons",
          },
          {
            key: "icons-dripicons",
            label: "Dripicons",
            url: "/ui/icons/dripicons",
            parentKey: "icons",
          },
          {
            key: "icons-font-awesome",
            label: "Font Awesome 5",
            url: "/ui/icons/font-awesome",
            parentKey: "icons",
          },
          {
            key: "icons-remix",
            label: "Remix icons",
            url: "/ui/icons/remix",
            parentKey: "icons",
          },
          {
            key: "icons-unicons",
            label: "Unicons",
            url: "/ui/icons/unicons",
            parentKey: "icons",
          },
        ],
      },
      {
        key: "maps",
        icon: "fe-map me-2",
        label: "Maps",
        parentKey: "components",
        children: [
          {
            key: "maps-google-maps",
            label: "Google maps",
            url: "/ui/maps/google-maps",
            parentKey: "maps",
          },
          {
            key: "maps-vector-maps",
            label: "Vector maps",
            url: "/ui/maps/vector-maps",
            parentKey: "maps",
          },
        ],
      },
    ],
  },
  {
    key: "pages",
    icon: "uil-copy-alt",
    label: "Pages",
    isTitle: true,
    children: [
      {
        key: "auth",
        icon: "fe-shield me-2",
        label: "Auth",
        parentKey: "pages",
        children: [
          {
            key: "auth-login",
            label: "Login",
            url: "/auth/login",
            parentKey: "auth",
          },
          {
            key: "auth-register",
            label: "Register",
            url: "/auth/register",
            parentKey: "auth",
          },
          {
            key: "auth-recover-password",
            label: "Recover Password",
            url: "/auth/recover-password",
            parentKey: "auth",
          },
          {
            key: "auth-lock-screen",
            label: "Lock Screen",
            url: "/auth/lock-screen",
            parentKey: "auth",
          },
          {
            key: "auth-logout",
            label: "Logout",
            url: "/auth/logout",
            parentKey: "auth",
          },
          {
            key: "auth-confirm-mail",
            label: "Confirm Mail",
            url: "/auth/confirm-mail",
            parentKey: "auth",
          },
        ],
      },
      {
        key: "error",
        icon: "fe-alert-circle me-2",
        label: "Error",
        parentKey: "pages",
        children: [
          {
            key: "error-404",
            label: "Error 404",
            url: "/error-404",
            parentKey: "error",
          },
          {
            key: "error-404-alt",
            label: "Error 404-alt",
            url: "/error-404-alt",
            parentKey: "error",
          },
          {
            key: "error-500",
            label: "Error 500",
            url: "/error-500",
            parentKey: "error",
          },
        ],
      },
      {
        key: "extra",
        icon: "fe-book-open me-2",
        label: "Extra Pages",
        parentKey: "pages",
        children: [
          {
            key: "pages-starter",
            label: "Starter Page",
            url: "/pages/starter",
            parentKey: "extra",
          },
          {
            key: "pages-timeline",
            label: "Timeline",
            url: "/pages/timeline",
            parentKey: "extra",
          },
          {
            key: "pages-profile",
            label: "Profile",
            url: "/pages/profile",
            parentKey: "extra",
          },
          {
            key: "pages-about",
            label: "About Us",
            url: "/pages/about",
            parentKey: "extra",
          },
          {
            key: "pages-contact",
            label: "Contact Us",
            url: "/pages/contact",
            parentKey: "extra",
          },
          {
            key: "pages-faq",
            label: "FAQs",
            url: "/pages/faq",
            parentKey: "extra",
          },
          {
            key: "pages-pricing",
            label: "Pricing",
            url: "/pages/pricing",
            parentKey: "extra",
          },
          {
            key: "pages-maintenance",
            label: "Maintenance",
            url: "/pages/maintenance",
            parentKey: "extra",
          },
          {
            key: "pages-coming-soon",
            label: "Coming Soon",
            url: "/pages/coming-soon",
            parentKey: "extra",
          },
          {
            key: "pages-invoice",
            label: "Invoice",
            url: "/pages/invoice",
            parentKey: "extra",
          },
        ],
      },
    ],
  },
  {
    key: "layouts",
    label: "Layouts",
    isTitle: false,
    icon: "fe-layout",
    children: [
      {
        key: "horizontal",
        label: "Horizontal",
        target: "_blank",
        url: "/horizontal",
        parentKey: "pages",
      },
      {
        key: "detached",
        label: "Detached",
        target: "_blank",
        url: "/detached",
        parentKey: "pages",
      },
      {
        key: "dark-mode",
        label: "Dark Mode",
        target: "_blank",
        url: "/dark-mode",
        parentKey: "pages",
      },
      {
        key: "compact-sidebar",
        label: "Compact",
        target: "_blank",
        url: "/compact-sidebar",
        parentKey: "pages",
      },
      {
        key: "icon-view",
        label: "Icon View",
        target: "_blank",
        url: "/icon-view",
        parentKey: "pages",
      },
      {
        key: "full-view",
        label: "Full View",
        target: "_blank",
        url: "/full-view",
        parentKey: "pages",
      },
    ],
  },
];
export { HORIZONTAL_MENU_ITEMS, MENU_ITEMS };
